INSERT INTO Person (first_name, last_name, age, gender, nation, field, parent_name, city) VALUES
('Ali', 'Valiyev', 30, 'Erkak', 'Uzbek', 'Dasturchi', 'Hasan Valiyev', 'Toshkent'),
('Laylo', 'Qodirova', 25, 'Ayol', 'Uzbek', 'Dasturchi', 'Olim Qodirov', 'Samarqand'),
('Aziz', 'Karimov', 22, 'Erkak', 'Uzbek', 'Muhandis', 'Akbar Karimov', 'Buxoro'),
('Gulnoza', 'Rahimova', 28, 'Ayol', 'Uzbek', 'Dizayner', 'Bahodir Rahimov', 'Xiva'),
('Olim', 'Toshpulatov', 35, 'Erkak', 'Uzbek', 'Ilmiy xodim', 'Javlon Toshpulatov', 'Namangan'),
('Mirzohid', 'Abdullayev', 32, 'Erkak', 'Uzbek', 'Huquqshunos', 'Ravshan Abdullayev', 'Andijon'),
('Sodiq', 'Xojayev', 29, 'Erkak', 'Uzbek', 'Shifokor', 'Ali Xojayev', 'Navoiy'),
('Madinabonu', 'Usmonova', 26, 'Ayol', 'Uzbek', 'Muhandis', 'Zafar Usmonov', 'Fargona'),
('Muhammad', 'Sharipov', 40, 'Erkak', 'Uzbek', 'Uqituvchi', 'Shukur Sharipov', 'Qashqadaryo'),
('Xurshida', 'Ergasheva', 27, 'Ayol', 'Uzbek', 'Talaba', 'Salim Ergashev', 'Sirdaryo'),
('Ibrohim', 'Rasulov', 24, 'Erkak', 'Uzbek', 'Iqtisodchi', 'Karim Rasulov', 'Jizzax'),
('Mahliyo', 'Eshonqulova', 31, 'Ayol', 'Uzbek', 'Buxgalter', 'Dilshod Eshonqulov', 'Surxondaryo'),
('Komil', 'Sodiqov', 29, 'Erkak', 'Uzbek', 'Arxitektor', 'Rustam Sodiqov', 'Qarshi'),
('Shahlo', 'Toraeva', 23, 'Ayol', 'Uzbek', 'Farmatsevt', 'Xurshid Toraev', 'Termiz'),
('Davron', 'Ismoilov', 34, 'Erkak', 'Uzbek', 'Sotuvchi', 'Turgun Ismoilov', 'Fargona'),
('Nigora', 'Ganiyeva', 28, 'Ayol', 'Uzbek', 'Talaba', 'Qobil Ganiyev', 'Guliston'),
('Javlon', 'Abduqodirov', 36, 'Erkak', 'Uzbek', 'Bankir', 'Safar Abduqodirov', 'Urganch'),
('Said', 'Kamalov', 30, 'Erkak', 'Uzbek', 'Huquqshunos', 'Zokir Kamalov', 'Toshkent'),
('Oydin', 'Sharipova', 26, 'Ayol', 'Uzbek', 'Muhandis', 'Zafar Sharipov', 'Andijon'),
('Rustam', 'Yusupov', 38, 'Erkak', 'Uzbek', 'Uqituvchi', 'Ismoil Yusupov', 'Samarqand'),
('Umid', 'Rasulov', 27, 'Erkak', 'Uzbek', 'Iqtisodchi', 'Karim Rasulov', 'Namangan'),
('Dilnoza', 'Eshonqulova', 24, 'Ayol', 'Uzbek', 'Dizayner', 'Dilshod Eshonqulov', 'Xiva'),
('Komil', 'Sodiqov', 32, 'Erkak', 'Uzbek', 'Arxitektor', 'Rustam Sodiqov', 'Qarshi'),
('Shahnoza', 'Toraeva', 22, 'Ayol', 'Uzbek', 'Farmatsevt', 'Xurshid Toraev', 'Termiz'),
('Diyor', 'Ismoilov', 39, 'Erkak', 'Uzbek', 'Sotuvchi', 'Turgun Ismoilov', 'Fargona'),
('Shirin', 'Ganiyeva', 31, 'Ayol', 'Uzbek', 'Talaba', 'Qobil Ganiyev', 'Guliston'),
('Sanjar', 'Abduqodirov', 36, 'Erkak', 'Uzbek', 'Bankir', 'Safar Abduqodirov', 'Urganch'),
('Elyor', 'Kamalov', 28, 'Erkak', 'Uzbek', 'Huquqshunos', 'Zokir Kamalov', 'Toshkent'),
('Madina', 'Sharipova', 30, 'Ayol', 'Uzbek', 'Muhandis', 'Zafar Sharipov', 'Andijon'),
('Sherzod', 'Yusupov', 40, 'Erkak', 'Uzbek', 'Uqituvchi', 'Ismoil Yusupov', 'Samarqand'),
('Ulugbek', 'Rasulov', 29, 'Erkak', 'Uzbek', 'Iqtisodchi', 'Karim Rasulov', 'Namangan'),
('Shahzoda', 'Eshonqulova', 25, 'Ayol', 'Uzbek', 'Dizayner', 'Dilshod Eshonqulov', 'Xiva'),
('Bekzod', 'Sodiqov', 33, 'Erkak', 'Uzbek', 'Arxitektor', 'Rustam Sodiqov', 'Qarshi'),
('Malika', 'Toraeva', 24, 'Ayol', 'Uzbek', 'Farmatsevt', 'Xurshid Toraev', 'Termiz'),
('Javohir', 'Ismoilov', 39, 'Erkak', 'Uzbek', 'Sotuvchi', 'Turgun Ismoilov', 'Fargona'),
('Yulduz', 'Ganiyeva', 29, 'Ayol', 'Uzbek', 'Talaba', 'Qobil Ganiyev', 'Guliston'),
('Sherali', 'Abduqodirov', 36, 'Erkak', 'Uzbek', 'Bankir', 'Safar Abduqodirov', 'Urganch'),
('Shoxruh', 'Kamalov', 27, 'Erkak', 'Uzbek', 'Huquqshunos', 'Zokir Kamalov', 'Toshkent'),
('Gulchehra', 'Sharipova', 26, 'Ayol', 'Uzbek', 'Muhandis', 'Zafar Sharipov', 'Andijon'),
('Husan', 'Yusupov', 34, 'Erkak', 'Uzbek', 'Uqituvchi', 'Ismoil Yusupov', 'Samarqand'),
('Qodir', 'Rasulov', 28, 'Erkak', 'Uzbek', 'Iqtisodchi', 'Karim Rasulov', 'Namangan'),
('Zebo', 'Eshonqulova', 23, 'Ayol', 'Uzbek', 'Dizayner', 'Dilshod Eshonqulov', 'Xiva'),
('Tohir', 'Sodiqov', 31, 'Erkak', 'Uzbek', 'Arxitektor', 'Rustam Sodiqov', 'Qarshi'),
('Dilshoda', 'Toraeva', 25, 'Ayol', 'Uzbek', 'Farmatsevt', 'Xurshid Toraev', 'Termiz'),
('Jamshid', 'Ismoilov', 36, 'Erkak', 'Uzbek', 'Sotuvchi', 'Turgun Ismoilov', 'Fargona'),
('Farangiz', 'Ganiyeva', 28, 'Ayol', 'Uzbek', 'Talaba', 'Qobil Ganiyev', 'Guliston'),
('Akbar', 'Abduqodirov', 39, 'Erkak', 'Uzbek', 'Bankir', 'Safar Abduqodirov', 'Urganch'),
('Shavkat', 'Kamalov', 33, 'Erkak', 'Uzbek', 'Huquqshunos', 'Zokir Kamalov', 'Toshkent');

-- Mana shu tarzda qolgan 50 ta yozuvni to'ldirishingiz mumkin


